### PR TITLE
bump to leanprover/lean4:v4.7.0

### PR DESCRIPTION
**Pull request by digama0**

### CODE REVIEW

**Comment by JamesGallicchio** [comment]
did lake CLI change again? CI is failing because `-Kdocs=on` isn't getting lake to pull the doc-gen conditional dependency :frowning_face:

**Comment by digama0** [comment]
try adding `-R`

**Comment by JamesGallicchio** [comment]
The CI already has `-R`. I think previously the manifest included `doc-gen`, and now doesn't, which is probably the issue.

I'll push the full manifest, but LMK if there is another recommended solution!

**Comment by JamesGallicchio** [comment]
that seems to have worked. merging!

**Pull request merged**
