### PR TITLE
Bump to leanprover/lean4:v4.5.0

### PR DESCRIPTION
**Pull request by T-Brick**
Updated to latest lean version; removed `ByteArray.ofFn` since that is now in std.

~~nvm waiting on doc-gen4 sob~~

Not sure if you want to tag the working `v4.5.0-rc1` commit like I did with my repos before merging.

### CODE REVIEW

**Comment by JamesGallicchio** [comment]
It seems like mathlib builds fine on v4.5.0 (with docgen4), if you run `lake update -Kdoc=on` it will include doc-gen4 in the manifest.

**Comment by T-Brick** [comment]
oops that make sense

had to fix mathlib to the `v4.5.0` release since i assume the `v4.6.0-rc1` release is now `master` and that was causing issues for me. i guess this project should be on `v4.6.0-rc1` now? its not at all clear to me what version of lean projects should actually be developed on, especially since it seems like the target for lean itself is monthly full+RC releases.

at the very least its good to have a working `v4.5.0` version

**Comment by JamesGallicchio** [comment]
I am still unsure how mathlib wants downstream libraries to be versioned... :(

We should probably have a similar scheme to mathlib where we make a v4.5.0 tag at v4.5.0 and then immediately move master to v4.6.0-rc1. Shouldn't be too much work to do once a month.

Anyways LGTM and will merge + tag at v4.5.0

**Comment by T-Brick** [comment]
yeah personally im sticking with calendar versioning -- kinda feels weird to attach the package version number to the version of Lean it runs on (especially since the toolchain just tells you what the Lean version is)

**Comment by JamesGallicchio** [comment]
last I recall, lake doesn't check or warn you if the lean version is not what it expects :,))))))) which is the root of all evil in lean packaging ecosystem. so being able to `@ "v4.5.0"` in the lakefile requires is a nice way to make sure your toolchains all match up until lake has a better solution.

**Pull request merged**
